version: '3.8'
services:
  api:
    build: .
    ports:
      - 8080:8080
    environment:
      DB_USERNAME: ${DB_USERNAME}
      DB_NAME: ${DB_NAME}
      DB_HOST: ${DB_HOST}
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}

  db:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - myvolume_test:/data/db
    command: [--auth]

volumes:
  myvolume_test:
    external: true

